<?php
/**
 * DocumentBaseConfigApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\ShopwareAdminApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shopware Admin API
 *
 * This endpoint reference contains an overview of all endpoints comprising the Shopware Admin API.  For a better overview, all CRUD-endpoints are hidden by default. If you want to show also CRUD-endpoints add the query parameter `type=jsonapi`.
 *
 * The version of the OpenAPI document: 6.5.8.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\ShopwareAdminApiClient\Test\Api;

use \OpenAPI\ShopwareAdminApiClient\Configuration;
use \OpenAPI\ShopwareAdminApiClient\ApiException;
use \OpenAPI\ShopwareAdminApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentBaseConfigApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\ShopwareAdminApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentBaseConfigApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDocumentBaseConfig
     *
     * Create a new Document Base Config resources..
     *
     */
    public function testCreateDocumentBaseConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDocumentBaseConfig
     *
     * Delete a Document Base Config resource..
     *
     */
    public function testDeleteDocumentBaseConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentBaseConfig
     *
     * Detailed information about a Document Base Config resource..
     *
     */
    public function testGetDocumentBaseConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDocumentBaseConfigList
     *
     * List with basic information of Document Base Config resources..
     *
     */
    public function testGetDocumentBaseConfigList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDocumentBaseConfig
     *
     * Partially update information about a Document Base Config resource..
     *
     */
    public function testUpdateDocumentBaseConfig()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
